main:
  cog x:
    legends:
      - { key: head_accel, id: [0], label: "x"}
      - { key: head_accel, id: [1], label: "y"}
      - { key: head_accel, id: [2], label: "z"}
      - { key: hic, id: [0]}
