extend:
  ../../common_plot.yaml
hic:
  func: plot_hic
  data:
    - { log: RobotHardware0_head_accel, column: [0,1,2]}
head_gyro:
  data:
    - { log: RobotHardware0_head_gyro, column: [0,1,2]}

head_accel:
  data:
    - { log: RobotHardware0_head_accel, column: [0,1,2]}
